### PR TITLE
feat: eslint@8 support

### PR DESCRIPTION
**Pull request by amilajack**
Fixes https://github.com/amilajack/eslint-plugin-compat/issues/488

### CODE REVIEW

**Comment by scsinke** [comment]
@amilajack Is there any more work that needs to be done?

**Comment by quicoto** [comment]
Any update on this PR?

Thank you

**Comment by amilajack** [comment]
This will be out by the end of today￼

**Comment by quicoto** [comment]
@amilajack I would love to help to push this, but on the failed check I don't know what to look at. Are we missing something code-wise?

Thank you

**Comment by amilajack** [comment]
@quicoto published to the `next` tag. Would be great if you or others could test this before I publish to `latest`

**Comment by quicoto** [comment]
@amilajack just tried the next tag, it worked. Feel free to publish.

Thank you

**Comment by amilajack** [comment]
Published to `latest`

**Pull request merged**
