### PR TITLE
feat: support flat config

### PR DESCRIPTION
**Pull request by nix6839**
# !! IMPORTANT !!
If user previously imported this package using ESM, `import { configs, rules } from 'eslint-plugin-compat'` will not work.

This is a BREAKING CHANGE, so need to increase a major version to release it.

If you agree to a major version upgrade,  it would be good to also remove `config`.

If you don't want to make a BREAKING CHANGE, I can maintain compatibility by splitting the package entry point into `.mts` and `.cts`. (I had implemented it once, but the code was too complicated, so I deleted it for now: https://github.com/amilajack/eslint-plugin-compat/commit/686d75a45bc84c33071ca36b5efb497fd0143044)

Please feel free to let me know which method you prefer. :)

## What's Changed
- Support flat config (Thank you for being a reference, [eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n)!)
- Bump dependencies
- Fix test errors with update snapshots
- Replace [babel-eslint](https://github.com/babel/babel-eslint) to [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) (See: https://github.com/babel/babel-eslint#note-babel-eslint-is-now-babeleslint-parser-and-has-moved-into-the-babel-monorepo)
- Deprecate named export
- Provide type declaration

Resolves: #603

P.S. [ESLint v9 has been released](https://github.com/eslint/eslint/releases/tag/v9.0.0). IMO, it's a good time to drop support for versions below ESLint v8.57.0!

### CODE REVIEW

**Comment by dargmuesli** [comment]
@amilajack now that eslint v9 is released, do you think merging this would be an option for you? :pray:

**Comment by amilajack** [comment]
Sorry for the delay here. I've published this as `eslint-plugin-compat@next`. Feel free to test, as I will as well.

**Comment by dargmuesli** [comment]
@nix6839 I understand that this PR only adds flat config support. I still want to mention that with ESLint v9.3.0 I get the [TypeError: context.getAncestors is not a function](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors()). Might be possible to fix this in this PR too as described under the link?

**Comment by nix6839** [comment]
> @nix6839 I understand that this PR only adds flat config support. I still want to mention that with ESLint v9.3.0 I get the [TypeError: context.getAncestors is not a function](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors()). Might be possible to fix this in this PR too as described under the link?

I think it's going to be a big task, so it should be worked on in a separate PR.

**Comment by amilajack** [comment]
> Might be possible to fix this in this PR too as described under the link?

@dargmuesli would you be interested in submitting a PR for this?

**Comment by dargmuesli** [comment]
> would you be interested in submitting a PR for this?

Out of time right now. Depending on other work on this I might come back to it in the future.

**Pull request merged**
