### PR TITLE
Update deps to pickup security patch to extend package

### LINKED ISSUE #129: Prototype pollution attack vulnerability
The current release of eslint-plugin-compat on npm (2.5.1) has a [prototype pollution attack vulnerability](https://hackerone.com/reports/381185), through its dependency on `mdn-browser-compat-data@0.0.40` > `extend@3.0.1`.

[A recent commit](https://github.com/amilajack/eslint-plugin-compat/commit/675b78b8e2373223c9e50758be6d757440a9b6e4) appears to have resolved the vulnerability, it just needs to be published to npm.

### PR DESCRIPTION
**Pull request by GreenGremlin**
Fixes #129

### CODE REVIEW

**Comment by GreenGremlin** [comment]
I was able to verify this fix by running `npm i eslint-plugin-compat@GreenGremlin/eslint-plugin-compat#patch-1` and testing it locally.

**Comment by amilajack** [comment]
Need to update the lockfile as well. Make sure to install with yarn

**Comment by GreenGremlin** [comment]
> Need to update the lockfile as well. Make sure to install with yarn

Done

**Comment by amilajack** [comment]
I just enabled renovate and [I merged the PR for it](https://github.com/amilajack/eslint-plugin-compat/pull/135). Will publish a release soon

**Comment by GreenGremlin** [comment]
Any update on when you might publish the update?

**Comment by amilajack** [comment]
Just pushed `v2.6.2`. Sorry for the delay on this

**Pull request closed without merging**
