### PR TITLE
Fixed broken recommended config path

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by ljharb** [comment]
Just curious, why the change from json to JS? Removing the extension makes perfect sense of course :-)

**Comment by amilajack** [comment]
I wanted to integrate `recommended.json` with babel so it could be included in production. Also i wasnt sure if `*.json` can be imported.

**Comment by ljharb** [comment]
`.json` can definitely be imported, it's part of node's require algorithm

**Comment by tbroyer** [comment]
Correct me if I'm wrong, but this "recommended" config cannot actually be used right? The plugin should export a `configs` key (per ESLint docs), but it exports a `config` one. Manually patching eslint-plugin-compat in my node_modules fixed it and I could use `extends: ["plugin:compat/recommended"]` in you `.eslintrc`, so it really looks like an oversight.

Should I open an issue?

**Comment by ljharb** [comment]
Please!

**Pull request merged**
