### PR TITLE
bump eslint peerDep to eslint@6

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by ljharb** [comment]
Make sure it’s added to CI too - if it’s not tested it’s not supported.

**Comment by amilajack** [comment]
Tests are passing with `eslint@6` but linting doesn't pass because of the following error:
```
Error: Failed to load plugin 'import' declared in 'package.json » eslint-config-bliss » eslint-config-ai
rbnb-base » /.../node_modules/eslint-config-airbnb-base/
rules/imports.js': Cannot find module 'eslint/lib/util/source-code'
Require stack:
```

**Comment by ljharb** [comment]
That might need to wait on the next version of the import plugin being published.

**Comment by tbroyer** [comment]
eslint-plugin-import 2.18.0 has been released: https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md

**Pull request merged**
