### PR TITLE
Fix error if stats have higher second range value.

### PR DESCRIPTION
**Pull request by yavorsky**
Now, if browserslist result includes ios safari (`> 4%` or just `last 1 ios version`), plugin throws error: `Cannot read property 'includes' of undefined`.
That's because `getUnsupportedTargets` compare keys from browserslist with keys from caniuse. Sometimes if versions is a range - it could be different.
For ex: for `ios_saf` browserslist returns `10-10.1`, and caniuse - `10-10.2`, so `stats['10-10.1']` returns undefined.
Current PR fixes this by comparing first values in ranges (they are static).

### CODE REVIEW

**Comment by amilajack** [comment]
Thanks for this 🎉🎉🎉 Would be great if some test cases could be added for this. They should go in the `Versioning.spec.js` file. Also the convention is to create a separate config file (see `test/multi-config.package.json`)

**Comment by yavorsky** [comment]
@amilajack 👍

**Comment by yavorsky** [comment]
@amilajack Just added test. Not to `Versioning.spec.js`, but created`CanIUseProvider.spec.js`. `Versioning` is more about browserslist versions, but we need to correct comparison browserslist vs caniuse with range values.

**Comment by amilajack** [comment]
🎉 Is this ready for merge?

**Comment by yavorsky** [comment]
@amilajack Yes 👌

**Comment by amilajack** [comment]
Will release this in a prerelease. Would be great if you could test out once more.

**Comment by yavorsky** [comment]
@amilajack 👍

**Comment by amilajack** [comment]
When running `npm run spec`, the tests failed. Getting the error `TypeError: Cannot read property 'includes' of undefined` in `src/providers/CanIUseProvider.js:95:34`

**Comment by amilajack** [comment]
Update: This was actually caused an inconsistency between the local caniuse and the browserslist caniuse databases. I'll fix this in another PR

**Comment by yavorsky** [comment]
@amilajack Good 👍 It's a little bit strange, but my tests are passed successfully. I think we have different caniuse/browserslist versions.

**Comment by amilajack** [comment]
@yavorsky Just published `1.0.2-0`. Would be great if you could test it out 😊

**Comment by yavorsky** [comment]
@amilajack Yes! Gladly! 👌

**Comment by andykenward** [comment]
@amilajack @yavorsky using `1.0.2-0` and setting browserslist to 

```
> 1%
not IE <= 11
```

Throws the error
```
Cannot read property 'includes' of undefined
TypeError: Cannot read property 'includes' of undefined
```

setting browserslist to 

```
last 2 versions
not IE <= 11
```

works

**Comment by amilajack** [comment]
This is probably related to https://github.com/amilajack/eslint-plugin-compat/issues/58, which was fixed in https://github.com/amilajack/eslint-plugin-compat/pull/59.

**Comment by andykenward** [comment]
@amilajack yep just tried #59 and it solved the issue for me. Thanks for the quick response.

**Comment by amilajack** [comment]
Pushing a new release right now @ `1.0.2-1` Would be great if you could test it out!

**Comment by andykenward** [comment]
@amilajack just tested `1.0.2-1`. Working fine for me, thanks.

**Pull request merged**
